// const pickIndexes = require('./cookbook/pickIndexes');
// const list = require('./cookbook/list');
// const cssQuery = require('./cookbook/cssQuery-setStyle').cssQuery;
// const setStyle = require('./cookbook/cssQuery-setStyle').setStyle;
// const disco = require('./cookbook/disco');
// require('./cookbook/get-n-function-calls');
// const dafaults = require('./cookbook/dafaults');
// const methodNames = require('./cookbook/methodNames');
// // const mapKeys = require('./cookbook/mapKeys');
// // const renameKeys = require('./cookbook/renameKeys');
const renameBy = require('./cookbook/renameBy');
